### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#98]
Docs build is working, but we need to document our whole code

**Comment by kordc** [comment]
@SebChw could you create a repository for publishing our docs? As the art is on your account. [Here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) is the tutorial

Then I'd add a github workflow action, that would push our docs to your .io site, and it'll be visible then on `https://sebchw.github.io/art/`


The config file would look like this:

```yaml
name: Build and Deploy Docs
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r docs/requirements.txt

    - name: Build documentation
      run: make -C docs html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
```
